### ISSUE TITLE
Progressive vegetable/tuber/legumes stage

### ISSUE THREAD

**Issue by devinsandberg** [PugmanD/Gti-Clicker#1]
While playing, once you've successfully clicked the potato (scoring 100 points), the potato should change into the following sequence of foods:

1. potato (100 pts, speed 1.0)
2. corn (125 pts, speed 1.2)
3. beet (150 pts, speed 1.4)

**Comment by PugmanD** [comment]
I made it turn to corn but how would I do it so it changes the speed and so when you click it the third time it turns to a beat?
